(function(d){var e=window.AmazonUIPageJS||window.P,g=e._namespace||e.attributeErrors,a=g?g("DetailPageMobileIconFarmAssets@common","DetailPageMobileIconFarm"):e;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,e,g){d.when("A").register("get-icon-farm-page-state",function(a){return{parseJSON:function(c){var b;try{b=a.$("#"+c).find('script[data-a-state\x3d"{"key":"iconfarm-state"}"]').html()}catch(f){console.log(f.message)}b?c=a.$.parseJSON(b):(a.state.parse(),
c=a.state("iconfarm-state"));return c}}});d.declare("iconfarm-metrics-constants",{ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",METRIC_TYPE:{GLANCE_VIEW:"GLANCE_VIEW",ICON_CLICK:"ICON_CLICK",SECONDARY_PAGE_OPEN:"SECONDARY_PAGE_OPEN",SECONDARY_PAGE_CLOSE:"SECONDARY_PAGE_CLOSE",FULL_RETURN_POLICY:"FULL_RETURN_POLICY",PAGE_DATA_MISSING:"PAGE_DATA_MISSING",ABSENT:"ABSENT"},REF_MARKER_PREFIX:{ICON_FARM_WIDGET:"iconfarm_wid",AMAZON_DELIVERED:"iconfarm_ad",
RETURNS_POLICY:"iconfarm_rp",PAY_ON_DELIVERY:"iconfarm_pod",WARRANTY:"iconfarm_wr",EASY_CARE:"iconfarm_ec",AMAZON_PROTECT:"iconfarm_ap",EBOOK_RETURNS_POLICY:"iconfarm_erp",EBOOK_PAY_ON_DELIVERY:"iconfarm_epod",GENERIC_RETURN_POLICY:"iconfarm_grp",MULTIPLE_SPECIFIC_RETURN_POLICY:"iconfarm_msrp",SINGLE_SPECIFIC_RETURN_POLICY:"iconfarm_ssrp"},REF_MARKER_SUFFIX:{GLANCE_VIEW:"_gv",ICON_CLICK:"_clk",SECONDARY_PAGE_OPEN:"_sp_op",SECONDARY_PAGE_CLOSE:"_sp_cl",FULL_RETURN_POLICY:"_frp",ABSENT:"_noavail"}});
d.when("A","iconfarm-return-policy-metric-logger","iconfarm-default-metric-logger").register("iconfarm-icon-metric-factory",function(a,c,b){return{getIconMetric:function(f){switch(f){case "RETURNS_POLICY":return c;default:return b}}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","get-icon-farm-page-state","iconfarm-icon-metric-factory").register("iconfarm-metricLogger",function(a,c,b,f,d){return{log:function(c,h,e){if(c&&h&&b.REF_MARKER_PREFIX[c]&&b.REF_MARKER_SUFFIX[h]){var k=
f.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV);k&&d.getIconMetric(c).log(c,h,a.$.extend(!0,{asin:k.asin,merchantId:k.merchantId},e))}}}});d.when("A","iconfarm-metric-cache").register("iconfarm-metricService",function(a,c){return{log:function(b){if(c.add(b)){var f="/ref\x3d"+b.ref,f=f+("?pageAsin\x3d"+b.asin),f=f+("\x26pageType\x3d"+(a.capabilities?a.capabilities.mobile?a.capabilities.isAmazonApp?"DetailWebView":"DetailAW":"Detail":"")),f=f+"\x26subPageType\x3dIconFarm"+("\x26merchantId\x3d"+b.merchantId);
a.get("/gp/product/ajax/dpx-metrics-handler.html"+f)}}}});d.register("iconfarm-postmetric",function(){return{postCountMetric:function(a){if("undefined"!==typeof a){var c=e.ue;if(c){var b=c.count(a)||0;c.count(a,b+1)}}},postTimeMetric:function(a,c){if("undefined"!==typeof a&&"undefined"!==typeof c){var b=e.ue;b&&b.count(a,c)}}}});d.when("A").register("iconfarm-metric-cache",function(a){var c=[],b=function(b){if(!(b&&b.asin&&b.merchantId&&b.ref))return!1;var d=!1;a.each(c,function(a,c){a.asin===b.asin&&
a.merchantId===b.merchantId&&a.ref===b.ref&&(d=!0)});return d};return{isPresent:b,add:function(a){return a&&a.asin&&a.merchantId&&a.ref?b(a)?!1:(c.push(a),!0):!1},reset:function(){c=[]}}});d.when("A","iconfarm-metricService","iconfarm-metrics-constants","iconfarm-postmetric").register("iconfarm-default-metric-logger",function(a,c,b,d){return{log:function(e,l,h){c.log(a.$.extend(!0,h,{ref:b.REF_MARKER_PREFIX[e]+b.REF_MARKER_SUFFIX[l]}));d.postCountMetric(b.REF_MARKER_PREFIX[e]+b.REF_MARKER_SUFFIX[l])}}});
d.when("A","iconfarm-metricService","iconfarm-metrics-constants","iconfarm-postmetric","get-icon-farm-page-state").register("iconfarm-return-policy-metric-logger",function(a,c,b,d,e){var l=function(){var a=e.parseJSON(b.ICON_FARM_PAGE_STATE_HOLDER_DIV);if(a&&a.RETURNS_POLICY&&a.RETURNS_POLICY.secondaryViewData&&a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies)switch(a.RETURNS_POLICY.secondaryViewData.glLevelReturnPolicies.length){case 0:return"GENERIC_RETURN_POLICY";case 1:return"SINGLE_SPECIFIC_RETURN_POLICY";
default:return"MULTIPLE_SPECIFIC_RETURN_POLICY"}};return{log:function(e,g,k){e=l()||e;c.log(a.$.extend(!0,k,{ref:b.REF_MARKER_PREFIX[e]+b.REF_MARKER_SUFFIX[g]}));d.postCountMetric(b.REF_MARKER_PREFIX[e]+b.REF_MARKER_SUFFIX[g])}}})});
/* ******** */
(function(f){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,a=h?h("DetailPageMobileIconFarmAssets@desktop","DetailPageMobileIconFarm"):g;a.guardFatal?a.guardFatal(f)(a,window):a.execute(function(){f(a,window)})})(function(f,g,h){f.when("A","a-popover","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants").register("icon-farm-desktop-popover",function(a,n,d,b,c){var e=function(e){var d=e.data("name");a.off("a:popover:beforeShow:"+d);a.on("a:popover:beforeShow:"+
d,function(a){b.log(d,c.METRIC_TYPE.ICON_CLICK);b.log(d,c.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:"+d);a.on("a:popover:beforeHide:"+d,function(a){b.log(d,c.METRIC_TYPE.SECONDARY_PAGE_CLOSE)})};return{init:function(){for(var b=a.$(d.ICON_FARM_CONTAINER_CLASS),c=0;c<b.length;c++){var k=a.$(b[c]),f=k.data(d.TYPE_PARAM);if(f&&f===d.TYPE_PARAM_VALUE_CUSTOM_POP_OVER){var f=k,m=a.$("#"+f.data(d.POPOVER_CONTENT_PARAM)),m={activate:d.POPOVER_ACTIVATION,position:d.POPOVER_POSITION,width:d.POPOVER_WIDTH,
inlineContent:m.html(),name:f.data("name")};n.create(f,m);e(k)}}}}});f.when("A","get-icon-farm-page-state","icon-farm-constants","iconfarm-metricLogger","iconfarm-metrics-constants","ready").register("icon-farm-desktop-returns-policy",function(a,f,d,b,c){a.declarative("returns-policy-url","click",function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.FULL_RETURN_POLICY);g.open(d.GENERIC_RETURNS_POLICY_URL,"_blank")});a.off("a:popover:beforeShow:return-policy-secondary-view");a.on("a:popover:beforeShow:return-policy-secondary-view",
function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.ICON_CLICK);b.log("RETURNS_POLICY",c.METRIC_TYPE.SECONDARY_PAGE_OPEN)});a.off("a:popover:beforeHide:return-policy-secondary-view");a.on("a:popover:beforeHide:return-policy-secondary-view",function(a){b.log("RETURNS_POLICY",c.METRIC_TYPE.SECONDARY_PAGE_CLOSE)});return{init:function(){var e=f.parseJSON(d.ICON_FARM_PAGE_STATE_HOLDER_DIV),b=a.$(d.ICON_FARM_SECONDARY_VIEW_HOLDER_ID);if(e&&e.RETURNS_POLICY&&e.RETURNS_POLICY.secondaryViewData&&e.RETURNS_POLICY.secondaryViewData.glLevelReturn)if(e&&
!e.returnPolicyContent){var c={responseType:"html"};c.data=JSON.stringify(e.RETURNS_POLICY.secondaryViewData);c.data&&a.ajax("/gp/product/features/icon-farm/iconFarm-sv-loader.html",{method:"POST",params:c,success:function(c){c&&b&&b.length&&(e.returnPolicyContent=c,a.state(d.ICON_FARM_STATE,e),b.html(c))}})}else e&&e.returnPolicyContent&&b&&b.length&&b.html(e.returnPolicyContent)}}});f.when("A","IconFarmPageStateParserService","icon-farm-desktop-popover","icon-farm-desktop-returns-policy","iconfarm-metricLogger",
"icon-farm-constants","iconfarm-metrics-constants","iconfarm-metric-cache","atf").execute(function(a,f,d,b,c,e,l,g){function k(){g.reset();a.loadImageManually(a.$(".icon-box"));d.init();b.init();h()}var h=function(){var b=a.$(".icon-container");b.length?c.log("ICON_FARM_WIDGET",l.METRIC_TYPE.GLANCE_VIEW):c.log("ICON_FARM_WIDGET",l.METRIC_TYPE.ABSENT);b.each(function(){c.log(a.$(this).data("name"),l.METRIC_TYPE.GLANCE_VIEW)})};k();a.on("a:pageUpdate",function(){var b;a:{try{if(a.$("#"+e.ICON_FARM_V2_FEATURE_DIV).find("script").length){b=
e.ICON_FARM_V2_FEATURE_DIV;break a}if(a.$("#"+e.ICON_FARM_V2_PRIMARY_FEATURE_DIV).find("script").length){b=e.ICON_FARM_V2_PRIMARY_FEATURE_DIV;break a}c.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}catch(d){c.log("ICON_FARM_WIDGET",l.PAGE_DATA_MISSING)}b=void 0}b&&f.isNewState(b,e.ICON_FARM_STATE)&&(b=f.processState(b,e.ICON_FARM_STATE),a.objectIsEmpty(b)||k())})});f.declare("icon-farm-constants",{GENERIC_RETURNS_POLICY_URL:"https://www.amazon.in/gp/help/customer/display.html?nodeId\x3d202111910",ICON_FARM_FEATURE_DIV:"iconFarm_feature_div",
ICON_FARM_V2_FEATURE_DIV:"iconfarmv2_feature_div",ICON_FARM_V2_PRIMARY_FEATURE_DIV:"iconFarmV2InsidePrimary_feature_div",ICON_FARM_PAGE_STATE_HOLDER_DIV:"iconfarm-pagestate-holder",ICON_FARM_CONTAINER_CLASS:".icon-container",ICON_FARM_SECONDARY_VIEW_HOLDER_ID:"#icon-farm-secondary-view-holder",ICON_FARM_STATE:"iconfarm-state",POPOVER_ACTIVATION:"onclick",POPOVER_POSITION:"triggerBottom",POPOVER_WIDTH:"533",POPOVER_CONTENT_PARAM:"iconContent",TYPE_PARAM:"type",TYPE_PARAM_VALUE:"bottom-sheet",TYPE_PARAM_VALUE_CUSTOM_POP_OVER:"custom-pop-over"});
(function(){f.when("A","atf").register("IconFarmPageStateParserService",function(a){function f(d,b){b='script[data-a-state\x3d"'+JSON.stringify({key:b})+'"]';return a.$("#"+d).find(b)}return{processState:function(d,b){var c;try{var e=f(d,b),g=e[0];c=e.html();var h=a.parseJSON(c);a.state(b,h);a.$.data(g,"state_processed",!0);return h}catch(k){console.log(k)}return a.state(b)},isNewState:function(d,b){try{return!a.$.data(f(d,b)[0],"state_processed")}catch(c){console.warn("Unable to determine state status",
c)}return!1}}})})()});
/* ******** */
